### ISSUE TITLE
Tried using it. Importing this modules results in a syntax error from within

### ISSUE THREAD

**Issue by pranav-xx** [evgenykochetkov/react-storybook-addon-props-combinations#15]
Hi,

This looks to be a really useful addon. However, when I tried importing it, I got syntax error "Unexpected token import". Not sure of the reason.

I can't share the code as I am coding in a client's VM

Thanks,
Pranav Kaushik

**Comment by evgenykochetkov** [comment]
Thank you! Fixed in v0.4.1
