### ISSUE TITLE
fails to build when uglified

### ISSUE THREAD

**Issue by joefraley** [evgenykochetkov/react-storybook-addon-props-combinations#17]
it looks like there's a stray line of jsx that doesn't build correctly using `@storybook/cli`'s `build-storybook` command.

**Comment by evgenykochetkov** [comment]
Hi! Sorry for delayed response.
Looks like it's related to https://github.com/storybooks/storybook/issues/1570
I used [a workaround](https://github.com/evgenykochetkov/react-storybook-addon-props-combinations/blob/master/.storybook/webpack.config.js) from that issue and it worked.
