### ISSUE TITLE
Feature request: support flow types

### ISSUE THREAD

**Issue by trevordmiller** [evgenykochetkov/react-storybook-addon-props-combinations#18]
Would be great if flow types were supported along with prop-types.

**Comment by evgenykochetkov** [comment]
This plugin relies on `react-docgen`, which is integrated in storybook with [`babel-plugin-react-docgen`](https://github.com/storybooks/babel-plugin-react-docgen). And `react-docgen` [has flow types support](https://github.com/reactjs/react-docgen#flow-type-support). So theoretically it should just work 😁 

If you have an example where it's broken — please share it, I would love to take a look.

**Comment by trevordmiller** [comment]
Ok thanks :)
