### ISSUE TITLE
Getting React unique keys warning

### ISSUE THREAD

**Issue by robertwbradford** [evgenykochetkov/react-storybook-addon-props-combinations#8]
This is a great tool. Thank you. I just tried it on a Button component that has some different combinations. However, I'm getting React's warning about unique keys:

```
warning.js?d66c:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in div
```

![screen shot 2016-12-27 at 4 27 24 pm](https://cloud.githubusercontent.com/assets/15946/21510534/bafb7186-cc51-11e6-80ce-94aae068733a.png)

**Comment by evgenykochetkov** [comment]
Thank you!
Fixed it in [v0.2.0](https://github.com/evgenykochetkov/react-storybook-addon-props-combinations/releases/tag/v0.2.0). 
Sorry for delay :)
